### ISSUE TITLE
error when edit the data

### ISSUE THREAD

**Issue by lyan6** [genenetwork/genenetwork#12]
Mouse
BHF2 (Apoe Null) UCLA
Phenotypes

[From Rob Email]
I get this error when I try to edit the data (I am trying to fix the sex assignments since some are obviously wrong in the file that they gave us).

Mod_python error: "PythonHandler main"
Traceback (most recent call last):
  File "/usr/lib64/python2.4/site-packages/mod_python/apache.py", line 299, in HandlerDispatch
    result = object(req)
  File "/gnshare/gn/web/webqtl/main.py", line 428, in handler
    page=DataUpdatePage.DataUpdatePage(fd)
  File "/gnshare/gn/web/webqtl/updateTrait/DataUpdatePage.py", line 92, in __init__
    self.updateResultPage(fd, thisTrait)
  File "/gnshare/gn/web/webqtl/updateTrait/DataUpdatePage.py", line 704, in updateResultPage
    raise ValueError
ValueError

**Comment by lyan6** [comment]
insert the following two strains:

SELECT * FROM Strain WHERE Strain.`Name` LIKE "B6HF2";
SELECT * FROM Strain WHERE Strain.`Name` LIKE "HB6F2";
