### ISSUE TITLE
problem with phenotype correlations

### ISSUE THREAD

**Issue by lyan6** [genenetwork/genenetwork#16]
[From Rob Email]

......
I get this problem with your data (which I tried when mine would not run).  When I pull up your CxB sample data, copy it, paste it into the trait data box, then try to run a phenotype correlation with published CxB phenotypes, I get the error.  I didn’t used to.
 
Could you send me the trait you are studying? There could be a problem with the data entry for one trait.
 
Even when I use your own sample CxB trait data, when I try to pull up phenotype correlations with published CxB phenotypes, I get the following error.  Whats up?
********
Traceback (most recent call last):
  File "/gnshare/gn/web/webqtl/cmdLine/webqtlCmdLine.py", line 96, in ?
    page = CorrelationPage.CorrelationPage(fd)
  File "/gnshare/gn/web/webqtl/cmdLine/../correlation/CorrelationPage.py", line 730, in __init__
    tblobj['body'], worksheet, corrScript = self.getTableBodyForPublish(myTrait=myTrait, traitList=traitList, formName=mainfmName, worksheet=worksheet, newrow=newrow, corrScript=corrScript, species=species)
  File "/gnshare/gn/web/webqtl/cmdLine/../correlation/CorrelationPage.py", line 1653, in getTableBodyForPublish
    gn2link = HT.Href(url="http://gn2.genenetwork.org/corr_scatter_plot?dataset_1=%s&dataset_2=%s&trait_1=%s&trait_2=%s" %
AttributeError: 'NoneType' object has no attribute 'db'

......

**Comment by lyan6** [comment]
Fixed.

https://github.com/genenetwork/genenetwork/commit/3b34a03af851e8dc81b20382a8c5b85b628cf7fc#diff-a9ecbe0ca3c8f82bfc1e6e2e402042c1
