### ISSUE TITLE
Error I got trying to download all phenotypes using Manager function

### ISSUE THREAD

**Issue by lyan6** [genenetwork/genenetwork#19]
[From Rob Email]

Mod_python error: "PythonHandler main"

Traceback (most recent call last):

  File "/usr/lib64/python2.4/site-packages/mod_python/apache.py", line 299, in HandlerDispatch
    result = object(req)

  File "/gnshare/gn/web/webqtl/main.py", line 384, in handler
    page = exportPhenotypeDatasetPage.exportPhenotypeDatasetPage(fd)

  File "/gnshare/gn/web/webqtl/management/exportPhenotypeDatasetPage.py", line 62, in __init__
    self.dict['body'] =  self.genInputPage()

  File "/gnshare/gn/web/webqtl/management/exportPhenotypeDatasetPage.py", line 74, in genInputPage
    self.cursor.execute('select PublishFreeze.Name from PublishFreeze, InbredSet where InbredSetId=InbredSet.Id')

  File "/usr/lib64/python2.4/site-packages/MySQLdb/cursors.py", line 173, in execute
    self.errorhandler(self, exc, value)

  File "/usr/lib64/python2.4/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue

OperationalError: (1052, "Column 'InbredSetId' in where clause is ambiguous")

**Comment by lyan6** [comment]
Fixed.

https://github.com/genenetwork/genenetwork/commit/c9599d19aeaff03a86d4af957de19b34edd8de2c
