### ISSUE TITLE
"Probes" function, KeyError: 'MDP'

### ISSUE THREAD

**Issue by lyan6** [genenetwork/genenetwork#22]
[From Rob Email]

http://gn2.genenetwork.org/show_trait?trait_id=1441508_at&dataset=JAX_CSB_L_0711

http://genenetwork.org/webqtl/main.py?FormID=showProbeInfo&database=JAX_CSB_L_0711&ProbeSetID=1441508_at&CellID=None&RISet=MDP&incparentsf1=ON

Mod_python error: "PythonHandler main"
Traceback (most recent call last):
  File "/usr/lib64/python2.4/site-packages/mod_python/apache.py", line 299, in HandlerDispatch
    result = object(req)
  File "/gnshare/gn/web/webqtl/main.py", line 91, in handler
    page = ShowProbeInfoPage.ShowProbeInfoPage(fd)
  File "/gnshare/gn/web/webqtl/showTrait/ShowProbeInfoPage.py", line 122, in __init__
    _f1, _f12, _mat, _pat = webqtlUtil.ParInfo[fd.RISet]
KeyError: 'MDP'

**Comment by lyan6** [comment]
Fixed.

https://github.com/genenetwork/genenetwork/commit/825ed50a9d029535a659d4dde726bf736204eae5
