### ISSUE TITLE
When add the traits to the shopping cart and ask to compute a correlation matrix get this error

### ISSUE THREAD

**Issue by lyan6** [genenetwork/genenetwork#25]
[From E-mail]

Mod_python error: "PythonHandler main"

Traceback (most recent call last):

  File "/usr/lib64/python2.4/site-packages/mod_python/apache.py", line 299, in HandlerDispatch
    result = object(req)

  File "/gnshare/gn/web/webqtl/main.py", line 230, in handler
    page = CorrelationMatrixPage.CorrelationMatrixPage(fd)

  File "/gnshare/gn/web/webqtl/correlationMatrix/CorrelationMatrixPage.py", line 220, in __init__
    _verboseName += ' on Chr %s @ %s Mb' % (thisTrait.chr,thisTrait.mb)

TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'

**Comment by lyan6** [comment]
https://github.com/genenetwork/genenetwork/commit/b52496b4dd5144bb5c88e601ca99f36c0072d02a

**Comment by lyan6** [comment]
Fixed.
