### ISSUE TITLE
Correlation Matrix error

### ISSUE THREAD

**Issue by lyan6** [genenetwork/genenetwork#29]
[From Rob Email]

I got this error message when working with the Group = Aged BXD
I was calculating correlations among phenotypes.

Mod_python error: "PythonHandler main"

Traceback (most recent call last):

  File "/usr/lib64/python2.4/site-packages/mod_python/apache.py", line 299, in HandlerDispatch
    result = object(req)

  File "/gnshare/gn/web/webqtl/main.py", line 230, in handler
    page = CorrelationMatrixPage.CorrelationMatrixPage(fd)

  File "/gnshare/gn/web/webqtl/correlationMatrix/CorrelationMatrixPage.py", line 401, in __init__
    pearsonEigenVectors=pearsonEigenVectors, form=form, fd=fd)

  File "/gnshare/gn/web/webqtl/correlationMatrix/CorrelationMatrixPage.py", line 516, in calcPCATraits
    dataArray = self.zScore(dataArray)

  File "/gnshare/gn/web/webqtl/correlationMatrix/CorrelationMatrixPage.py", line 588, in zScore
    data2 = map(lambda x:(x-mean)/stdev,data)

  File "/gnshare/gn/web/webqtl/correlationMatrix/CorrelationMatrixPage.py", line 588, in 
    data2 = map(lambda x:(x-mean)/stdev,data)

ZeroDivisionError: float division

**Comment by lyan6** [comment]
https://github.com/genenetwork/genenetwork/commit/281772f0f1ba8f17fbfa7293c7dedc6e11de0dcb

**Comment by lyan6** [comment]
Fixed.
