### ISSUE TITLE
Literature Correlation error

### ISSUE THREAD

**Issue by lyan6** [genenetwork/genenetwork#35]
Human
GTEx v5
Esophagus Mucosa mRNA
Cdc20

Literature Correlation (top 5000)

Traceback (most recent call last):
  File "/gnshare/gn/web/webqtl/cmdLine/webqtlCmdLine.py", line 96, in ?
    page = CorrelationPage.CorrelationPage(fd)
  File "/gnshare/gn/web/webqtl/cmdLine/../correlation/CorrelationPage.py", line 373, in __init__
    traitdatabase, dataStartPos = self.fetchAllDatabaseData(species=species, GeneId=input_trait_GeneId, GeneSymbol=input_trait_symbol, strains=_strains, db=self.db, method=self.method, returnNumber=self.returnNumber, tissueProbeSetFreezeId=TissueProbeSetFreezeId)
  File "/gnshare/gn/web/webqtl/cmdLine/../correlation/CorrelationPage.py", line 1012, in fetchAllDatabaseData
    tempTable = self.getTempLiteratureTable(species=species, input_species_geneid=GeneId, returnNumber=returnNumber)
  File "/gnshare/gn/web/webqtl/cmdLine/../correlation/CorrelationPage.py", line 1140, in getTempLiteratureTable
    self.cursor.execute( 'INSERT INTO %s (GeneId1, GeneId2, value) VALUES (%d,%d,%f)' % (tmpTableName_2, int(input_species_geneid),int(translated_species_geneid), float(lit_corr_alue)) )
  File "/usr/lib64/python2.4/site-packages/MySQLdb/cursors.py", line 173, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python2.4/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
IntegrityError: (1062, "Duplicate entry '1179' for key 'PRIMARY'")

**Comment by lyan6** [comment]
Fixed.

https://github.com/genenetwork/genenetwork/commit/5da366e0b62f1ec276c9aa01b90d9dafe5608016
