### ISSUE TITLE
Trait Data update error

### ISSUE THREAD

**Issue by lyan6** [genenetwork/genenetwork#41]
Mod_python error: "PythonHandler main"

Traceback (most recent call last):

  File "/usr/lib64/python2.4/site-packages/mod_python/apache.py", line 299, in HandlerDispatch
    result = object(req)

  File "/gnshare/gn/web/webqtl/main.py", line 428, in handler
    page=DataUpdatePage.DataUpdatePage(fd)

  File "/gnshare/gn/web/webqtl/updateTrait/DataUpdatePage.py", line 96, in __init__
    self.updateResultPage(fd, thisTrait)

  File "/gnshare/gn/web/webqtl/updateTrait/DataUpdatePage.py", line 712, in updateResultPage
    raise ValueError

ValueError

**Comment by lyan6** [comment]
Loaded new BXD strains into database.

https://github.com/genenetwork/genenetwork/commit/80e51032957c23ad670e6a8863bba47dbc941e44

**Comment by lyan6** [comment]
Fixed.
